config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :tasks do
    member do
      get 'update_status/:new_status', action: :update_status, as: :update_status # rota para mudar o status
    end
  end 
  get 'dashboard', to: 'dashboard#index' # rota para dashboard
  root to: "tasks#index"
  get 'home', to: 'home#index'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index

        
        # pegar a qauntidade de tasks com To Do
        @todo_count = ActiveRecord::Base.connection.execute("SELECT COUNT(*) FROM tasks WHERE status = 'To Do'")
        @todo = @todo_count.getvalue(0, 0) # formata o número para inteiro

        @doing_count = ActiveRecord::Base.connection.execute("SELECT COUNT(*) FROM tasks WHERE status = 'Doing'")
        @doing = @doing_count.getvalue(0, 0)

        @done_count = ActiveRecord::Base.connection.execute("SELECT COUNT(*) FROM tasks WHERE status = 'Done'")
        @done = @done_count.getvalue(0, 0)

        # pega os os meses de cada tarefa onde o status seja Done
        res = ActiveRecord::Base.connection.execute("select DISTINCT(EXTRACT(MONTH FROM created_at)) AS month from tasks where status = 'Done'")
        @meses_done = res.map { |x| x["month"].to_i } # converte as saídas para inteiro

    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
    @todo_tasks = Task.where(status: 'To Do')
    @doing_tasks = Task.where(status: 'Doing')
    @done_tasks = Task.where(status: 'Done')
    @quantidade_todo = @todo_tasks.count
    @quantidade_doing = @doing_tasks.count
    @quantidade_done = @done_tasks.count
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end
  puts "siiiii #{ENV["APP_RAILWAY_DATABASE_PASSWORD"]}"
  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task) }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task) }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /tasks/1/update_status/Done
  def update_status
    @task = Task.find(params[:id])

    new_status = params[:new_status] # Recuperar o novo status da URL

    if @task.update(status: new_status)
      redirect_to tasks_path
    else
      redirect_to tasks_path
    end

    
  end
  

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Contact was successfully destroyed."}
      format.json { head :no_content }
    end
  end

  private 
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :description, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/dashboard/index.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>

<%= stylesheet_link_tag 'dashboard' %> <!-- Inclua seu arquivo SCSS aqui -->

<div id="cabecalho">
  <%= link_to "Tarefas", root_path, id: "tasks" %>
</div>
<h1>Dashboard</h1>

<div id="graficos"> 
  <canvas id="pizza" style="max-width: 400px"></canvas>
  <canvas id="barra" style="max-width: 400px"></canvas>
</div>

<script>
  var xLinha = []
  xLinha = <%= @meses_done %> //Quantidade de de vezes que um mês teve uma tarefa concluída ex: [9, 9, 9] significa que tiveram 3 no mes 9

  xLinha.sort(function(a, b) { //ordenar a lista do menor para o maior
    return a - b;
  });
  var listaSemRepetir = [] 
  for (let i = 0; i<xLinha.length; i++){ //for usado para pegar xLinha sem repetir nenhum mês, para saber quais meses tiveram tarefas concluídas
    if (xLinha[i]!=xLinha[i-1]){
      listaSemRepetir.push(xLinha[i])
    }
  }

  for (let i = 0; i<listaSemRepetir.length; i++){ //trocar número por nome
    switch (listaSemRepetir[i]) {
    case 1:
      listaSemRepetir[i] = "Janeiro";
      break;
    case 2: 
      listaSemRepetir[i] = "Fevereiro";
      break;
    case 3:
      listaSemRepetir[i] = "Março";
      break;
    case 4:
      listaSemRepetir[i] = "Abril";
      break;
    case 5:
      listaSemRepetir[i] = "Maio";
      break;
    case 6:
      listaSemRepetir[i] = "Junho";
      break;
    case 7:
      listaSemRepetir[i] = "Julho";
      break;
    case 8:
      listaSemRepetir[i] = "Agosto";
      break;
    case 9:
      listaSemRepetir[i] = "Setembro";
      break;
    case 10:
      listaSemRepetir[i] = "Outubro";
      break;
    case 11:
      listaSemRepetir[i] = "Novembro";
      break;
    case 12:
      listaSemRepetir[i] = "Dezembro";
      break;
    default:
      listaSemRepetir[i] = "Mês inválido";
    }
  }
  var yBarra = []
  for(let i = 0; i<xLinha.length; i++){ //for para transformar xLinha em uma lista com a quantidade de tarefas concluídas por mês ex: [9, 9, 9, 10] vira [3, 1] 
    if(i==0){
      yBarra.push(1) //cria um elemento com valor 1
    }
    else if(xLinha[i]==xLinha[i-1]){
      yBarra[yBarra.length-1] += 1 //adiciona +1 no último elemento

    }
    else if(xLinha[i]!=xLinha[i-1]){
      yBarra.push(1) //cria mais um elemento com valor 1

    }
  }
  var xPizza = ["To Do", "Doing", "Done"];
  var yPizza = [<%= @todo %>, <%= @doing %>, <%= @done %>, 0]; // quantidade de tarefas todo, doing e done
  var pizzaColors = [
    "#b91d47",
    "#00aba9",
    "#2b5797",
    "#e8c3b9",
    "#1e7145"
  ];

  new Chart("pizza", {
    type: "bar",
    data: {
      labels: xPizza,
      datasets: [{
        backgroundColor: pizzaColors,
        data: yPizza
      }]
    },
    options: {
      legend: {display: false}


    }

  });

  var xBarra = listaSemRepetir;

  new Chart("barra", {
    type: "line",
    data: {
      labels: xBarra,
      datasets: [{
        fill: false,
        lineTension: 0,
        backgroundColor:"rgba(0,0,255,1.0)",
        borderColor: "rgba(0,0,255,0.1)",
        data: yBarra
      }]
    },
    options: {
      legend: {display: false}


    }
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Listas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'tasks', media: 'all' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1>Hello, Alex!</h1>

app/views/tasks/_form.html.erb
<%= stylesheet_link_tag 'form' %>
<div id="divpai">
  <%= form_with(model: task, html: {class: "form"}) do |form| %> <!-- Form de criar e editar tarefas --> 
    <div class= "ae">
      <div>
        <%= form.label :"Nome:", style: "display: block" %>
        <%= form.text_field :name, class: "barraembaixo"  %>
      </div>

      <div>
        <%= form.label :"Descrição:", style: "display: block"%>
        <%= form.text_area :description, rows: 4, columns: 50,  class: "barraembaixo"  %>
      </div>
    </div>

    <div class="nocentro">
      <%= form.label :status %>
      <%= form.select :status, ['To Do', 'Doing', 'Done'] %>
    </div>

    <div class="nocentro">
      <%= form.submit "Salvar" %>
    </div>
  <% end %>
</div>

app/views/tasks/_task.html.erb
<body> <!-- Usado para motrar a task -->
  <div id="botoes">
    <%= link_to "Editar a Tarefa", edit_task_path(@task), id: "edit", class: "button"%>
    <%= link_to "Voltar Para Tarefas", tasks_path, id: "back", class: "button" %>
    <%= button_to "Apagar", @task, method: :delete, id: "delete", class: "button" %>
  </div>
  <div id="<%= dom_id task %>" class="task">
    <p style="margin-left: 12px; font-size: 20px">
      <strong>Título:</strong>
      <%= task.name %>
    </p>
    <p style="margin-left: 12px; font-size: 20px">
      <strong>Descrição:</strong>
      <%= task.description %>
    </p>
  </div>
  <%= stylesheet_link_tag 'show'%>
</body>

app/views/tasks/edit.html.erb
<body style="padding: 0">
  <div id="minhaDiv">
    <%= link_to "Mostra a Tarefa", @task, id: "back"%> 
    <%= link_to "Voltar Para Tarefas", tasks_path, id: "back2" %>
  </div>
  <div id="divPaiVerde"> <!-- criei uma nova div por cima para poder usar justify content sem usar o body -->
    <div style="background-color: rgba(1, 209, 164, 0.349); width: 400px; text-align: center; border-radius: 15px;" id="formVerde">
      <h1 style="text-align: center">Editando a Tarefa</h1>
      <%= render "form", task: @task %> 
      <br>
    </div>
  </div>
</body>

app/views/tasks/index.html.erb
<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script
src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js">
</script>



<div id="botoes">
  <%= link_to "Nova Tarefa", new_task_path, class: "link", id: "new" %>
  <%= link_to "Dashboard", dashboard_path, class: "link", id: "dash" %>
</div>

<div id="tasks" class="container">
  <!-- No códgio: três divs classe sortable que são as colunas kanban-->
  <div class="sortable" id="To Do"> 
    <h2>A fazer</h2>  
    <% @todo_tasks.each do |task| %> <!-- @todo_task = tasks com status todo-->
      <div data-task-id="<%= task.id %>" class="drag" id="task_todo">
          <div>
            <p class="descricao">
              <strong>Título:</strong>
              <%= task.name %>
            </p>
            <p class="descricao">
              <strong>Descrição:</strong>
              <%= task.description %>
            </p>
          </div>
          <%= link_to "Mostrar a Tarefa", task %>
      </div>
    <% end %>
  </div>
  <div class="sortable" id="Doing">
    <h2>Em progresso</h2>
    <% @doing_tasks.each do |task| %>
      <div data-task-id="<%= task.id %>" class="drag" id="task_doing">
          <div>
          <p class="descricao">
            <strong>Título:</strong>
            <%= task.name %>
          </p>
          <p class="descricao">
            <strong>Descrição:</strong>
            <%= task.description %>
          </p>
          </div>
          <%= link_to "Mostrar a Tarefa", task %>
      </div>
    <% end %>
  </div>
  <div class="sortable" id="Done">
    <h2>Concluídas</h2>
    <% @done_tasks.each do |task| %>
      <div data-task-id="<%= task.id %>" class="drag" id="task_done">
          <div>
          <p class="descricao">
            <strong>Título:</strong>
            <%= task.name %>
          </p>
          <p class="descricao">
            <strong>Descrição:</strong>
            <%= task.description %>
          </p>
          </div>
          <%= link_to "Mostrar a Tarefa", task %>
      </div>

    <% end %>
  </div>

</div>

<script>
  var quantidade_todo = <%= @quantidade_todo %>
  var quantidade_doing = <%= @quantidade_doing %>
  var quantidade_done = <%= @quantidade_done %>
  $(function() {
    var taskId;

  $(".sortable").sortable({
    connectWith: ".sortable", //para conectar o sortable nas três colunas
    items: ".drag",
    start: function(event, ui) {
      taskId = ui.item.data("task-id");
    },
    update: function(event, ui) {
      var divId = ui.item.parent().attr("id"); //pega o id da nova coluna kanban

      $.ajax({ //requisição pra mudar o status sempre que a task for solta
          url: "/tasks/" + taskId + "/update_status/" + divId,
          method: "GET"
      });
      }
      });
    });
 </script>

app/views/tasks/new.html.erb
<body style="padding: 0">
  <div id="minhaDiv">
    <%= link_to "Voltar Para Tarefas", tasks_path, id: "back" %>
  </div>
  <div id="divPaiVerde">
    <div style="background-color: rgba(1, 209, 164, 0.349); width: 400px; text-align: center; border-radius: 15px;" id="formVerde">
      <h1 style="text-align: center">Nova Tarefa</h1>

      <%= render "form", task: @task %>
    </div>
  </div>
</body>

app/views/tasks/show.html.erb
<%= stylesheet_link_tag 'show'%>
<%= render @task %>